package sipay.catalogs;

import org.json.JSONObject;

public class Currency {
    JSONObject CURRENCIES = new JSONObject();

    public Currency() {
        this.CURRENCIES.put("AED", new String[]{"AED", "784", "2", "Dírham de los Emiratos Árabes Unidos"});
        this.CURRENCIES.put("AED", new String[]{"AED", "784", "2", "Dírham de los Emiratos Árabes Unidos"});
        this.CURRENCIES.put("AFN", new String[]{"AFN", "971", "2", "Afgani"});
        this.CURRENCIES.put("ALL", new String[]{"ALL", "8", "2", "Lek"});
        this.CURRENCIES.put("AMD", new String[]{"AMD", "51", "2", "Dram armenio"});
        this.CURRENCIES.put("ANG", new String[]{"ANG", "532", "2", "Florín antillano neerlandés"});
        this.CURRENCIES.put("AOA", new String[]{"AOA", "973", "2", "Kwanza"});
        this.CURRENCIES.put("ARS", new String[]{"ARS", "32", "2", "Peso argentino"});
        this.CURRENCIES.put("AUD", new String[]{"AUD", "36", "2", "Dólar australiano"});
        this.CURRENCIES.put("AWG", new String[]{"AWG", "533", "2", "Florín arubeño"});
        this.CURRENCIES.put("AZN", new String[]{"AZN", "944", "2", "Manat azerbaiyano"});
        this.CURRENCIES.put("BAM", new String[]{"BAM", "977", "2", "Marco convertible"});
        this.CURRENCIES.put("BBD", new String[]{"BBD", "52", "2", "Dólar de Barbados"});
        this.CURRENCIES.put("BDT", new String[]{"BDT", "50", "2", "Taka"});
        this.CURRENCIES.put("BGN", new String[]{"BGN", "975", "2", "Lev búlgaro"});
        this.CURRENCIES.put("BHD", new String[]{"BHD", "48", "3", "Dinar bareiní"});
        this.CURRENCIES.put("BIF", new String[]{"BIF", "108", "0", "Franco de Burundi"});
        this.CURRENCIES.put("BMD", new String[]{"BMD", "60", "2", "Dólar bermudeño"});
        this.CURRENCIES.put("BND", new String[]{"BND", "96", "2", "Dólar de Brunéi"});
        this.CURRENCIES.put("BOB", new String[]{"BOB", "68", "2", "Boliviano"});
        this.CURRENCIES.put("BOV", new String[]{"BOV", "984", "2", "MVDOL"});
        this.CURRENCIES.put("BRL", new String[]{"BRL", "986", "2", "Real brasileño"});
        this.CURRENCIES.put("BSD", new String[]{"BSD", "44", "2", "Dólar bahameño"});
        this.CURRENCIES.put("BTN", new String[]{"BTN", "64", "2", "Ngultrum"});
        this.CURRENCIES.put("BWP", new String[]{"BWP", "72", "2", "Pula"});
        this.CURRENCIES.put("BYR", new String[]{"BYR", "974", "0", "Rublo bielorruso"});
        this.CURRENCIES.put("BZD", new String[]{"BZD", "84", "2", "Dólar beliceño"});
        this.CURRENCIES.put("CAD", new String[]{"CAD", "124", "2", "Dólar canadiense"});
        this.CURRENCIES.put("CDF", new String[]{"CDF", "976", "2", "Franco congoleño"});
        this.CURRENCIES.put("CHE", new String[]{"CHE", "947", "2", "Euro WIR"});
        this.CURRENCIES.put("CHF", new String[]{"CHF", "756", "2", "Franco suizo"});
        this.CURRENCIES.put("CHW", new String[]{"CHW", "948", "2", "Franco WIR"});
        this.CURRENCIES.put("CLF", new String[]{"CLF", "990", "4", "Unidad de fomento"});
        this.CURRENCIES.put("CLP", new String[]{"CLP", "152", "0", "Peso chileno"});
        this.CURRENCIES.put("CNY", new String[]{"CNY", "156", "2", "Yuan chino"});
        this.CURRENCIES.put("COP", new String[]{"COP", "170", "2", "Peso colombiano"});
        this.CURRENCIES.put("COU", new String[]{"COU", "970", "2", "Unidad de valor real"});
        this.CURRENCIES.put("CRC", new String[]{"CRC", "188", "2", "Colón costarricense"});
        this.CURRENCIES.put("CUC", new String[]{"CUC", "931", "2", "Peso convertible"});
        this.CURRENCIES.put("CUP", new String[]{"CUP", "192", "2", "Peso cubano"});
        this.CURRENCIES.put("CVE", new String[]{"CVE", "132", "2", "Escudo caboverdiano"});
        this.CURRENCIES.put("CZK", new String[]{"CZK", "203", "2", "Corona checa"});
        this.CURRENCIES.put("DJF", new String[]{"DJF", "262", "0", "Franco yibutiano"});
        this.CURRENCIES.put("DKK", new String[]{"DKK", "208", "2", "Corona danesa"});
        this.CURRENCIES.put("DOP", new String[]{"DOP", "214", "2", "Peso dominicano"});
        this.CURRENCIES.put("DZD", new String[]{"DZD", "12", "2", "Dinar argelino"});
        this.CURRENCIES.put("EGP", new String[]{"EGP", "818", "2", "Libra egipcia"});
        this.CURRENCIES.put("ERN", new String[]{"ERN", "232", "2", "Nakfa"});
        this.CURRENCIES.put("ETB", new String[]{"ETB", "230", "2", "Birr etíope"});
        this.CURRENCIES.put("EUR", new String[]{"EUR", "978", "2", "Euro"});
        this.CURRENCIES.put("FJD", new String[]{"FJD", "242", "2", "Dólar fiyiano"});
        this.CURRENCIES.put("FKP", new String[]{"FKP", "238", "2", "Libra malvinense"});
        this.CURRENCIES.put("GBP", new String[]{"GBP", "826", "2", "Libra esterlina"});
        this.CURRENCIES.put("GEL", new String[]{"GEL", "981", "2", "Lari"});
        this.CURRENCIES.put("GHS", new String[]{"GHS", "936", "2", "Cedi ghanés"});
        this.CURRENCIES.put("GIP", new String[]{"GIP", "292", "2", "Libra de Gibraltar"});
        this.CURRENCIES.put("GMD", new String[]{"GMD", "270", "2", "Dalasi"});
        this.CURRENCIES.put("GNF", new String[]{"GNF", "324", "0", "Franco guineano"});
        this.CURRENCIES.put("GTQ", new String[]{"GTQ", "320", "2", "Quetzal"});
        this.CURRENCIES.put("GYD", new String[]{"GYD", "328", "2", "Dólar guyanés"});
        this.CURRENCIES.put("HKD", new String[]{"HKD", "344", "2", "Dólar de Hong Kong"});
        this.CURRENCIES.put("HNL", new String[]{"HNL", "340", "2", "Lempira"});
        this.CURRENCIES.put("HRK", new String[]{"HRK", "191", "2", "Kuna"});
        this.CURRENCIES.put("HTG", new String[]{"HTG", "332", "2", "Gourde"});
        this.CURRENCIES.put("HUF", new String[]{"HUF", "348", "2", "Forinto"});
        this.CURRENCIES.put("IDR", new String[]{"IDR", "360", "2", "Rupia indonesia"});
        this.CURRENCIES.put("ILS", new String[]{"ILS", "376", "2", "Nuevo shéquel israelí"});
        this.CURRENCIES.put("INR", new String[]{"INR", "356", "2", "Rupia india"});
        this.CURRENCIES.put("IQD", new String[]{"IQD", "368", "3", "Dinar iraquí"});
        this.CURRENCIES.put("IRR", new String[]{"IRR", "364", "2", "Rial iraní"});
        this.CURRENCIES.put("ISK", new String[]{"ISK", "352", "0", "Corona islandesa"});
        this.CURRENCIES.put("JMD", new String[]{"JMD", "388", "2", "Dólar jamaiquino"});
        this.CURRENCIES.put("JOD", new String[]{"JOD", "400", "3", "Dinar jordano"});
        this.CURRENCIES.put("JPY", new String[]{"JPY", "392", "0", "Yen"});
        this.CURRENCIES.put("KES", new String[]{"KES", "404", "2", "Chelín keniano"});
        this.CURRENCIES.put("KGS", new String[]{"KGS", "417", "2", "Som"});
        this.CURRENCIES.put("KHR", new String[]{"KHR", "116", "2", "Riel"});
        this.CURRENCIES.put("KMF", new String[]{"KMF", "174", "0", "Franco comorense"});
        this.CURRENCIES.put("KPW", new String[]{"KPW", "408", "2", "Won norcoreano"});
        this.CURRENCIES.put("KRW", new String[]{"KRW", "410", "0", "Won"});
        this.CURRENCIES.put("KWD", new String[]{"KWD", "414", "3", "Dinar kuwaití"});
        this.CURRENCIES.put("KYD", new String[]{"KYD", "136", "2", "Dólar de las Islas Caimán"});
        this.CURRENCIES.put("KZT", new String[]{"KZT", "398", "2", "Tenge"});
        this.CURRENCIES.put("LAK", new String[]{"LAK", "418", "2", "Kip"});
        this.CURRENCIES.put("LBP", new String[]{"LBP", "422", "2", "Libra libanesa"});
        this.CURRENCIES.put("LKR", new String[]{"LKR", "144", "2", "Rupia de Sri Lanka"});
        this.CURRENCIES.put("LRD", new String[]{"LRD", "430", "2", "Dólar liberiano"});
        this.CURRENCIES.put("LSL", new String[]{"LSL", "426", "2", "Loti"});
        this.CURRENCIES.put("LYD", new String[]{"LYD", "434", "3", "Dinar libio"});
        this.CURRENCIES.put("MAD", new String[]{"MAD", "504", "2", "Dírham marroquí"});
        this.CURRENCIES.put("MDL", new String[]{"MDL", "498", "2", "Leu moldavo"});
        this.CURRENCIES.put("MGA", new String[]{"MGA", "969", "2", "Ariary malgache"});
        this.CURRENCIES.put("MKD", new String[]{"MKD", "807", "2", "Denar"});
        this.CURRENCIES.put("MMK", new String[]{"MMK", "104", "2", "Kyat"});
        this.CURRENCIES.put("MNT", new String[]{"MNT", "496", "2", "Tugrik"});
        this.CURRENCIES.put("MOP", new String[]{"MOP", "446", "2", "Pataca"});
        this.CURRENCIES.put("MRO", new String[]{"MRO", "478", "2", "Uquiya"});
        this.CURRENCIES.put("MUR", new String[]{"MUR", "480", "2", "Rupia de Mauricio"});
        this.CURRENCIES.put("MVR", new String[]{"MVR", "462", "2", "Rufiyaa"});
        this.CURRENCIES.put("MWK", new String[]{"MWK", "454", "2", "Kwacha"});
        this.CURRENCIES.put("MXN", new String[]{"MXN", "484", "2", "Peso mexicano"});
        this.CURRENCIES.put("MXV", new String[]{"MXV", "979", "2", "Unidad de Inversión (UDI) mexicana"});
        this.CURRENCIES.put("MYR", new String[]{"MYR", "458", "2", "Ringgit malayo"});
        this.CURRENCIES.put("MZN", new String[]{"MZN", "943", "2", "Metical mozambiqueño"});
        this.CURRENCIES.put("NAD", new String[]{"NAD", "516", "2", "Dólar namibio"});
        this.CURRENCIES.put("NGN", new String[]{"NGN", "566", "2", "Naira"});
        this.CURRENCIES.put("NIO", new String[]{"NIO", "558", "2", "Córdoba"});
        this.CURRENCIES.put("NOK", new String[]{"NOK", "578", "2", "Corona noruega"});
        this.CURRENCIES.put("NPR", new String[]{"NPR", "524", "2", "Rupia nepalí"});
        this.CURRENCIES.put("NZD", new String[]{"NZD", "554", "2", "Dólar neozelandés"});
        this.CURRENCIES.put("OMR", new String[]{"OMR", "512", "3", "Rial omaní"});
        this.CURRENCIES.put("PAB", new String[]{"PAB", "590", "2", "Balboa"});
        this.CURRENCIES.put("PEN", new String[]{"PEN", "604", "2", "Sol"});
        this.CURRENCIES.put("PGK", new String[]{"PGK", "598", "2", "Kina"});
        this.CURRENCIES.put("PHP", new String[]{"PHP", "608", "2", "Peso filipino"});
        this.CURRENCIES.put("PKR", new String[]{"PKR", "586", "2", "Rupia pakistaní"});
        this.CURRENCIES.put("PLN", new String[]{"PLN", "985", "2", "Złoty"});
        this.CURRENCIES.put("PYG", new String[]{"PYG", "600", "0", "Guaraní"});
        this.CURRENCIES.put("QAR", new String[]{"QAR", "634", "2", "Riyal qatarí"});
        this.CURRENCIES.put("RON", new String[]{"RON", "946", "2", "Leu rumano"});
        this.CURRENCIES.put("RSD", new String[]{"RSD", "941", "2", "Dinar serbio"});
        this.CURRENCIES.put("RUB", new String[]{"RUB", "643", "2", "Rublo ruso"});
        this.CURRENCIES.put("RWF", new String[]{"RWF", "646", "0", "Franco ruandés"});
        this.CURRENCIES.put("SAR", new String[]{"SAR", "682", "2", "Riyal saudí"});
        this.CURRENCIES.put("SBD", new String[]{"SBD", "90", "2", "Dólar de las Islas Salomón"});
        this.CURRENCIES.put("SCR", new String[]{"SCR", "690", "2", "Rupia seychelense"});
        this.CURRENCIES.put("SDG", new String[]{"SDG", "938", "2", "Dinar sudanés"});
        this.CURRENCIES.put("SEK", new String[]{"SEK", "752", "2", "Corona sueca"});
        this.CURRENCIES.put("SGD", new String[]{"SGD", "702", "2", "Dólar de Singapur"});
        this.CURRENCIES.put("SHP", new String[]{"SHP", "654", "2", "Libra de Santa Elena"});
        this.CURRENCIES.put("SLL", new String[]{"SLL", "694", "2", "Leone"});
        this.CURRENCIES.put("SOS", new String[]{"SOS", "706", "2", "Chelín somalí"});
        this.CURRENCIES.put("SRD", new String[]{"SRD", "968", "2", "Dólar surinamés"});
        this.CURRENCIES.put("SSP", new String[]{"SSP", "728", "2", "Libra sursudanesa"});
        this.CURRENCIES.put("STD", new String[]{"STD", "678", "2", "Dobra"});
        this.CURRENCIES.put("SVC", new String[]{"SVC", "222", "2", "Colon Salvadoreño"});
        this.CURRENCIES.put("SYP", new String[]{"SYP", "760", "2", "Libra siria"});
        this.CURRENCIES.put("SZL", new String[]{"SZL", "748", "2", "Lilangeni"});
        this.CURRENCIES.put("THB", new String[]{"THB", "764", "2", "Baht"});
        this.CURRENCIES.put("TJS", new String[]{"TJS", "972", "2", "Somoni tayiko"});
        this.CURRENCIES.put("TMT", new String[]{"TMT", "934", "2", "Manat turcomano"});
        this.CURRENCIES.put("TND", new String[]{"TND", "788", "3", "Dinar tunecino"});
        this.CURRENCIES.put("TOP", new String[]{"TOP", "776", "2", "Paʻanga"});
        this.CURRENCIES.put("TRY", new String[]{"TRY", "949", "2", "Lira turca"});
        this.CURRENCIES.put("TTD", new String[]{"TTD", "780", "2", "Dólar de Trinidad y Tobago"});
        this.CURRENCIES.put("TWD", new String[]{"TWD", "901", "2", "Nuevo dólar taiwanés"});
        this.CURRENCIES.put("TZS", new String[]{"TZS", "834", "2", "Chelín tanzano"});
        this.CURRENCIES.put("UAH", new String[]{"UAH", "980", "2", "Grivna"});
        this.CURRENCIES.put("UGX", new String[]{"UGX", "800", "0", "Chelín ugandés"});
        this.CURRENCIES.put("USD", new String[]{"USD", "840", "2", "Dólar estadounidense"});
        this.CURRENCIES.put("USN", new String[]{"USN", "997", "2", "Dólar estadounidense (Siguiente día)"});
        this.CURRENCIES.put("UYI", new String[]{"UYI", "940", "0", "Peso en Unidades Indexadas (Uruguay)"});
        this.CURRENCIES.put("UYU", new String[]{"UYU", "858", "2", "Peso uruguayo"});
        this.CURRENCIES.put("UZS", new String[]{"UZS", "860", "2", "Som uzbeko"});
        this.CURRENCIES.put("VEF", new String[]{"VEF", "937", "2", "Bolívar"});
        this.CURRENCIES.put("VND", new String[]{"VND", "704", "0", "Dong vietnamita"});
        this.CURRENCIES.put("VUV", new String[]{"VUV", "548", "0", "Vatu"});
        this.CURRENCIES.put("WST", new String[]{"WST", "882", "2", "Tala"});
        this.CURRENCIES.put("XAF", new String[]{"XAF", "950", "0", "Franco CFA de África Central"});
        this.CURRENCIES.put("XAG", new String[]{"XAG", "961", "-1", "Plata (una onza troy)"});
        this.CURRENCIES.put("XAU", new String[]{"XAU", "959", "-1", "Oro (una onza troy)"});
        this.CURRENCIES.put("XBA", new String[]{"XBA", "955", "-1", "Unidad compuesta europea (EURCO) (Unidad del mercados de bonos)"});
        this.CURRENCIES.put("XBB", new String[]{"XBB", "956", "-1", "Unidad Monetaria europea (E.M.U.-6) (Unidad del mercado de bonos)"});
        this.CURRENCIES.put("XBC", new String[]{"XBC", "957", "-1", "Unidad europea de cuenta 9 (E.U.A.-9) (Unidad del mercado de bonos)"});
        this.CURRENCIES.put("XBD", new String[]{"XBD", "958", "-1", "Unidad europea de cuenta 17 (E.U.A.-17) (Unidad del mercado de bonos)"});
        this.CURRENCIES.put("XCD", new String[]{"XCD", "951", "2", "Dólar del Caribe Oriental"});
        this.CURRENCIES.put("XDR", new String[]{"XDR", "960", "-1", "Derechos especiales de giro"});
        this.CURRENCIES.put("XOF", new String[]{"XOF", "952", "0", "Franco CFA de África Occidental"});
        this.CURRENCIES.put("XPD", new String[]{"XPD", "964", "-1", "Paladio (una onza troy)"});
        this.CURRENCIES.put("XPF", new String[]{"XPF", "953", "0", "Franco CFP"});
        this.CURRENCIES.put("XPT", new String[]{"XPT", "962", "-1", "Platino (una onza troy)"});
        this.CURRENCIES.put("XSU", new String[]{"XSU", "994", "-1", "SUCRE"});
        this.CURRENCIES.put("XTS", new String[]{"XTS", "963", "-1", "Reservado para pruebas"});
        this.CURRENCIES.put("XUA", new String[]{"XUA", "965", "-1", "Unidad de cuenta BAD"});
        this.CURRENCIES.put("XXX", new String[]{"XXX", "999", "-1", "Sin divisa"});
        this.CURRENCIES.put("YER", new String[]{"YER", "886", "2", "Rial yemení"});
        this.CURRENCIES.put("ZAR", new String[]{"ZAR", "710", "2", "Rand"});
        this.CURRENCIES.put("ZMW", new String[]{"ZMW", "967", "2", "Kwacha zambiano"});
        this.CURRENCIES.put("ZWL", new String[]{"ZWL", "932", "2", "Dólar zimbabuense"});
    }

    public Object find(String currency) {
        return CURRENCIES.opt(currency);
    }
}